layout_spectrum: 0.2379162
typography_spectrum: 0
color:
  saturation: 0.2151184
  lightness: 0.0911959
  brandStrength: 0.9298463
  brandColors:
    - '#FFFFFF'
    - '#011630'
    - '#B5917F'
    - '#6ECF89'
    - '#306F91'
  rhythmicContrast: 0.393676
name: Seniors by Nancy Center
